TestProject.Web/Controllers/BookingController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using TestProject.Domain.Entities;
using TestProject.Domain.Handlers;
using TestProject.Web.Models;

namespace TestProject.Web.Controllers
{
    [Authorize]
    public class BookingController : Controller
    {
        private readonly IBookingHandler _bookingHandler;
        private readonly IMapper _mapper;
        public BookingController(IBookingHandler bookingHandler, IMapper mapper)
        {
            _bookingHandler = bookingHandler;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var bookings = _bookingHandler.GetBooking().ToList();
            var bookingsViewModel = new List<BookingQueryViewModel>();

            bookings.ForEach(x =>
            {
                var newItem = new BookingQueryViewModel()
                {
                    Days = x.Days,
                    EndDate = x.EndDate.ToShortDateString(),
                    EndExpectedDate = x.EndExpectedDate.ToShortDateString(),
                    LicensePlate = _bookingHandler.GetLicensePlateById(x.MotorcycleId),
                    StartDate = x.StartDate.ToShortDateString(),
                    Value = x.Value,
                    Username = _bookingHandler.GetUserNameById(x.UserId)
                };
                bookingsViewModel.Add(newItem);
            });
            return View(bookingsViewModel);
        }

        public IActionResult Create(ObjectId motorcycleId)
        {
            var model = new BookingViewModel()
            {
                MotorcycleId = motorcycleId,
                StartDate = DateTime.Today.AddDays(1),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Confirm(ConfirmBookingViewModel model)
        {
            try
            {
                if (model.EndDate <= model.StartDate)
                    throw new Exception("End date can't be lower than start date!");

                if (model.Days == 0)
                    throw new Exception("You need to select days");

                Booking booking = new Booking()
                {
                    Days = model.Days,
                    StartDate = model.StartDate,
                    EndDate = model.EndDate,
                    MotorcycleId = model.MotorcycleId,
                };
                model.Value = _bookingHandler.CalculeBookingValue(booking);
                model.EndExpectedDate = model.StartDate.AddDays(model.Days);
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["ResultErrorMessage"] = "error: " + ex.Message;
                return RedirectToAction("Create", new { model.MotorcycleId });

            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(ConfirmBookingViewModel model)
        {
            try
            {
                var user = _bookingHandler.GetUserByUsername(User.Identity.Name);

                if (user.CnhType == Domain.Enums.CnhType.Car)
                    throw new Exception("You need a CNH type A or AB to rent a motorcycle!");


                Booking booking = new Booking()
                {
                    UserId = user.Id,
                    Days = model.Days,
                    EndDate = model.EndDate,
                    EndExpectedDate = model.EndExpectedDate,
                    MotorcycleId = model.MotorcycleId,
                    StartDate = model.StartDate,
                    Value = model.Value
                };

                _bookingHandler.CreateBooking(booking);
                TempData["ResultSuccessMessage"] = "Booking confirmed!";
                return RedirectToAction("Index", "Motorcycle");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }

        }
    }
}

TestProject.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using TestProject.Domain.Entities;
using TestProject.Domain.Handlers;
using TestProject.Web.Models;

namespace TestProject.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderHandler _orderHandler;
        public OrderController(IOrderHandler orderHandler)
        {
            _orderHandler = orderHandler;
        }
        public IActionResult Index()

        {
            // _orderHandler.Teste("oi");
            var order = _orderHandler.GetOrders();
            var list = new List<OrderViewModel>();


            foreach (var orderItem in order)
            {
                var newItem = new OrderViewModel()
                {
                    CreationDate = orderItem.CreationDate,
                    Id = orderItem.Id,
                    LicensePlate = _orderHandler.GetLicensePlateById(orderItem.MotorcycleId),
                    Price = orderItem.Price,
                    Status = orderItem.Status,
                    UserName = _orderHandler.GetUserNameById(orderItem.UserId)

                };
                list.Add(newItem);
            }

            return View(list.AsEnumerable());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(decimal price)
        {
            _orderHandler.CreateOrder(price);
            return View();
        }

        [HttpPost]
        public IActionResult Update(OrderViewModel viewModel)
        {
            try
            {
                Order order = new Order()
                {
                    CreationDate = viewModel.CreationDate,
                    Id = viewModel.Id,
                    MotorcycleId = viewModel.MotorcycleId,
                    Price = viewModel.Price,
                    Status = Domain.Enums.StatusType.Accepted,
                    UserId = viewModel.UserId
                };

                _orderHandler.UpdateOrder(order);
                TempData["ResultSuccessMessage"] = "Order Accepted!";
                return RedirectToAction("Index");

            }
            catch(Exception ex)
            {
                TempData["ResultErrorMessage"] = "error: " + ex.Message;
                return RedirectToAction("Index");
            }


        }
        public IActionResult GetOrder(ObjectId id)
        {
            try
            {
                var order = _orderHandler.GetOrder(id, User.Identity.Name);

                var orderViewModel = new OrderViewModel()
                {
                    CreationDate = order.CreationDate,
                    LicensePlate = _orderHandler.GetLicensePlateById(order.MotorcycleId),
                    Price = order.Price,
                    Status = order.Status,
                    UserName = User.Identity.Name,
                    UserId = order.UserId,
                    MotorcycleId = order.MotorcycleId
                };
                TempData["ResultSuccessMessage"] = "Order Accepted!";
                return View(orderViewModel);
            }
            catch (Exception ex)
            {
                TempData["ResultErrorMessage"] = "error: " + ex.Message;
                return RedirectToAction("Index");

            }
        }

        public IActionResult Deliver(ObjectId id)
        {
            try
            {
                _orderHandler.DeliverOrder(id);

                TempData["ResultSuccessMessage"] = "Order Delivered!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ResultErrorMessage"] = "error: " + ex.Message;
                return RedirectToAction("Index");

            }
        }


    }
}

TestProject.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestProject.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestProject.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestProject.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1  d-flex justify-content-start">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Motorcycle" asp-action="Index">Motorcycles</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Bookings</a>
                            </li>
                        }
                        <li class="nav-item"> 
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                    </ul>

                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <ul class="navbar-nav flex-grow-1  d-flex justify-content-end">

                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@User.Identity.Name </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Logout" class="btn btn-secondary">Logout</a>
                            </li>

                        </ul>
                    }
                    <u id="Message"></u>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TestProject.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
    <title>SignalR Notification</title>
    
<body>
    <div id="notificationArea"></div>

    <script>
        "use strict";
        var connection = new signalR.HubConnectionBuilder()
            .withUrl("/notificationHub")
            .configureLogging(signalR.LogLevel.Information)
            .build();

        connection.start()
            .then(() => console.log("Conexão SignalR estabelecida com sucesso"))
            .catch(err => console.error("Erro ao estabelecer conexão SignalR:", err));

        connection.on("ReceiveMessage", function (message) {
            console.log(message);
            var msg = message.Text;
            var li = document.createElement("li");
            li.textContent = msg;
            document.getElementById("Message").appendChild("li");
        });
    </script>
</body>
</html>